### ISSUE TITLE
Switch QC data loading from `register_sample.pl` to `register_sample.py`

### ISSUE THREAD

**Issue by alkc** [bjhall/nextflow_wgs#87]
I want to be able to sort wgs QC data on run date and integrate w/ clarity QC in CDM

To that end the process that creates the instructions for CDM need to be updated to use the new `register_sample.py` script, to make use of lims_id and run_date/sequencing_date vars

## TODO
- [ ] Change CDM process to save instructions for `register_sample.py` to a .cdmpy file
- [ ] Update middleman if necessary?
- [ ] Update CDM if necessary
